### PR TITLE
Freeze status

### PR DESCRIPTION
**Pull request by pburnsdata**
# Issues 
#46 
#40

### CODE REVIEW

**Comment by pburnsdata** [comment]
changes are tiny and in the last two commits

**Comment by pburnsdata** [comment]
Changes are small and in the last 3 commits. Right now the form level freeze column is empty which is why it's returning NAs - I asked Heather if that was intentional, but in the meantime I just filled it with zeros, so when this is merged there wont be NaN% in the ready for freeze column anymore)

**Comment by samussiah** [comment]
just saw your comment @pburnsdata .  somehow the data file grew to 60 megs/1,000,000 records so i removed all those extra rows.  would you ask Heather to remove any columns we don't need?

**Comment by pburnsdata** [comment]
yeah I just messaged her, she said she'll do that when she gets back from the break. The from level freeze column was also not supposed to be empty and she updated it. So in the meantime, I'll use the updated data and just drop the unnecessary columns for our test data manually and she'll make it part of the SAS process when she gets back.

**Pull request merged**
